name: NASA Daily News

on:
  schedule:
    - cron: '0 12 * * *' # Roda todo dia às 09:00 (Brasília)
  workflow_dispatch: # Permite rodar manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: os-actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run NASA Bot
        env:
          NASA_KEY: ${{ secrets.NASA_KEY }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python nasabot.py
