name: NASA Daily News

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 12 * * *' # Todo dia às 09:00 (Horário de Brasília)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests deep-translator

      - name: Run NASA Bot
        run: python nasabot.py
